import streamlit as st
import pandas as pd
from datetime import datetime

# ==========================================
# PAGE CONFIGURATION (Institutional Look)
# ==========================================
st.set_page_config(
    page_title="BG STAR PRO | Signal Terminal",
    page_icon="⭐",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for clean, professional look
st.markdown("""
    <style>
    .big-font { font-size:20px !important; font-weight: bold; }
    .signal-card { padding: 15px; border-radius: 5px; margin-bottom: 10px; background-color: #1E1E1E; }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# MOCK DATA (In production, load this from SQLite/JSON generated by app.py)
# ==========================================
# This simulates the data broadcasted by MasterSignalBot
def get_latest_signals():
    return [
        {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "coin": "BTC",
            "action": "BUY",
            "signal_type": "🟢 Strong Signal",
            "score": 92,
            "triggers": ["BOS/CHOCH", "Volume Spike"],
            "news_status": "BULLISH",
            "ai_status": "CONFIRMED",
            "ai_confidence": 95,
            "reason": "Technical breakout aligns with positive macro news, highly probable continuation."
        },
        {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "coin": "ETH",
            "action": "SELL",
            "signal_type": "🟠 Confirmed by News",
            "score": 88,
            "triggers": ["Liquidity Sweep", "HTF Alignment"],
            "news_status": "BEARISH",
            "ai_status": "WAIT (Skipped)",
            "ai_confidence": 0,
            "reason": "News confirmed bearish sentiment, AI skipped due to missing API criteria."
        },
        {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "coin": "SOL",
            "action": "BUY",
            "signal_type": "🟡 Technical Signal",
            "score": 78,
            "triggers": ["Order Block Touch"],
            "news_status": "NEUTRAL",
            "ai_status": "SKIPPED",
            "ai_confidence": 0,
            "reason": "Score below 85 / News Neutral. Pure technical play."
        }
    ]

# ==========================================
# SIDEBAR: API HEALTH & SYSTEM STATUS
# ==========================================
with st.sidebar:
    st.title("⚙️ System Status")
    st.markdown("---")
    
    st.subheader("API Limits (Estimated)")
    st.progress(85, text="News API (85% Remaining)")
    st.progress(92, text="Gemini AI (92% Remaining)")
    
    st.markdown("---")
    st.subheader("Active Engines")
    st.success("✅ Technical Scanner (Live)")
    st.success("✅ Smart Trigger Engine (Live)")
    st.success("✅ News Engine (Standby)")
    st.success("✅ Gemini AI (Standby)")
    
    st.markdown("---")
    st.caption("BG STAR PRO strictly follows Event-Driven API calls to minimize latency and cost.")

# ==========================================
# MAIN DASHBOARD
# ==========================================
st.title("⭐ BG STAR PRO")
st.markdown('<p class="big-font">Institutional Smart API Trigger Terminal</p>', unsafe_allow_html=True)
st.markdown("---")

# Fetch Data
signals = get_latest_signals()

if not signals:
    st.info("No active signals at the moment. Waiting for market triggers...")
else:
    # Creating a DataFrame for the compact table view
    df_signals = pd.DataFrame(signals)
    
    # Selecting and renaming columns for the UI based on Blueprint
    display_df = df_signals[[
        "timestamp", "coin", "signal_type", "action", 
        "score", "triggers", "news_status", "ai_status", "ai_confidence"
    ]].copy()
    
    display_df.columns = [
        "Time", "Asset", "Signal Tier", "Action", 
        "Tech Score", "Smart Triggers", "News", "AI", "Confidence %"
    ]

    st.subheader("📡 Live Signal Feed")
    
    # Display as an interactive dataframe
    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True
    )
    
    st.markdown("---")
    st.subheader("🧠 AI Logic & Reasoning Breakdown")
    
    # Detailed Cards for each signal's reasoning
    for sig in signals:
        with st.container():
            st.markdown(f"**{sig['signal_type']} | {sig['coin']} - {sig['action']}**")
            
            col1, col2 = st.columns([1, 4])
            with col1:
                st.metric(label="Technical Score", value=f"{sig['score']}/100")
            with col2:
                st.info(f"**Trigger Events:** {', '.join(sig['triggers'])}")
                if sig['reason']:
                    st.write(f"**AI/System Reason:** {sig['reason']}")
            
            st.divider()


